language: python
python:
  - "3.8"

services: mysql
env:

  - DJANGO=3.0.5 DJANGO_SETTINGS_MODULE="demacian_justice.settings"
install:
  - pip install -q Django==$DJANGO
  - pip install pep8
  - pip install mysqlclient
  - pip install -U python-dotenv

before_script:
  - mysql -e 'create database demacian_justice;'
script:
  - python ./demacian_justice/manage.py test
