# Generated by Django 3.0.5 on 2020-04-27 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('puuid', models.CharField(max_length=100, unique=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=datetime.datetime(2020, 4, 27, 9, 25, 33, 84948))),
                ('updated_at', models.DateField(default=datetime.datetime(2020, 4, 27, 9, 25, 33, 84966))),
            ],
        ),
    ]
