# Generated by Django 3.0.5 on 2020-05-18 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('karma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='name',
        ),
        migrations.AlterField(
            model_name='summoner',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
